# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cosine_pb2 as cosine__pb2


class CosineStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCos = channel.unary_unary(
                '/cosine.Cosine/GetCos',
                request_serializer=cosine__pb2.CosRequest.SerializeToString,
                response_deserializer=cosine__pb2.CosReply.FromString,
                )


class CosineServicer(object):
    """The greeting service definition.
    """

    def GetCos(self, request, context):
        """getCos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CosineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCos,
                    request_deserializer=cosine__pb2.CosRequest.FromString,
                    response_serializer=cosine__pb2.CosReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosine.Cosine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cosine(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetCos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cosine.Cosine/GetCos',
            cosine__pb2.CosRequest.SerializeToString,
            cosine__pb2.CosReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
